[phases.setup]
nixPkgs = ["nodejs-18_x", "postgresql"]
aptPkgs = ["libpq-dev", "build-essential"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p /app/static",
  "cp -r frontend/dist/* /app/static/",
  "chmod +x start.sh"
]

[start]
cmd = "./start.sh"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"